version: '3.2'

services:
    admin:
        build:
            context: ./admin
        volumes:
            - ./admin:/admin
            - static_volume:/admin/files/static
            - media_volume:/admin/files/media
        networks:
            - union-network
    server:
        build:
            context: ./nginx
        volumes:
            - static_volume:/admin/files/static
            - media_volume:/admin/files/media
        ports:
            - 443:443
            - 80:8000
        depends_on:
            - admin
        networks:
            - union-network

    bot:
        build:
            context: ./bot
        networks:
            - union-network
        depends_on:
            - server
            - admin
 
volumes:
    static_volume:
    media_volume:
              
networks:
    union-network: