version: '3.2'

services:
    admin:
        build:
            context: ./admin
        ports:
            - 8000:8000
        networks:
            - union-network

    bot:
        build:
            context: ./bot
        networks:
            - union-network
        depends_on:
            - admin
            
networks:
    union-network: