# Generated by Django 3.1.4 on 2021-07-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0002_auto_20210718_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Оглавление поста')),
                ('points', models.IntegerField(default=0, verbose_name='Количество баллов ')),
                ('top', models.IntegerField(default=0, verbose_name='Количество нажатий на топ месяца')),
                ('tooday', models.IntegerField(default=0, verbose_name='Количество нажатий на сегодня')),
                ('yesterday', models.IntegerField(default=0, verbose_name='Количество нажатий на вчера')),
                ('questions', models.IntegerField(default=0, verbose_name='Количество отвеченных вопросов')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
