# Generated by Django 3.1.4 on 2021-07-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'start_game_photo'), (1, 'start_game_joke')], default=1, verbose_name='Действие')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие пользователей',
                'verbose_name_plural': 'Действия пользователей',
            },
        ),
    ]
