# Generated by Django 3.1.4 on 2021-07-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_posts_paid'),
        ('user', '0002_auto_20210721_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='action',
        ),
        migrations.AddField(
            model_name='actions',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='index.game', verbose_name='вопрос'),
        ),
    ]
