# Generated by Django 3.1.4 on 2021-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210726_0929'),
        ('user', '0003_auto_20210721_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='humans',
            field=models.ManyToManyField(to='index.Human'),
        ),
    ]
