# Generated by Django 3.1.4 on 2021-07-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210726_0929'),
        ('user', '0004_user_humans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='humans',
            field=models.ManyToManyField(blank=True, to='index.Human'),
        ),
    ]
