# Generated by Django 3.1.4 on 2021-07-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210726_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='humans',
        ),
        migrations.CreateModel(
            name='Idols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humans', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='humans', to='user.user', verbose_name='Кумиры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кумир',
                'verbose_name_plural': 'Кумиры',
            },
        ),
    ]
