# Generated by Django 3.1.4 on 2021-07-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210726_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idols',
            name='humans',
        ),
        migrations.AddField(
            model_name='idols',
            name='human',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='humans', to='user.user', verbose_name='Кумир'),
        ),
    ]
