# Generated by Django 3.1.4 on 2021-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210726_0929'),
        ('user', '0008_auto_20210726_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idols',
            name='human',
        ),
        migrations.AddField(
            model_name='idols',
            name='humans',
            field=models.ManyToManyField(related_name='humans', to='index.Human', verbose_name='Кумиры'),
        ),
    ]
