# Generated by Django 3.1.4 on 2021-07-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210726_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Оглавление')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='push', verbose_name='Фото поста')),
            ],
            options={
                'verbose_name': 'Кумир',
                'verbose_name_plural': 'Кумиры',
            },
        ),
    ]
