# Generated by Django 3.1.4 on 2021-08-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_push'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='push',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='push',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='push', verbose_name='Фото уведомления'),
        ),
    ]
