# Generated by Django 3.1.7 on 2021-08-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_push_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tooday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='top',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yesterday',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Токен пользователя'),
        ),
    ]
