# Generated by Django 3.1.4 on 2021-07-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя человека')),
                ('describe', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выступающий',
                'verbose_name_plural': 'Выступающие',
            },
        ),
        migrations.CreateModel(
            name='TypeOfPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа поста')),
                ('describe', models.TextField(verbose_name='Описание типа')),
            ],
            options={
                'verbose_name': 'Тип поста',
                'verbose_name_plural': 'Типы постов',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Оглавление поста')),
                ('describe', models.TextField(verbose_name='Описание поста')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('cost', models.CharField(blank=True, max_length=200, verbose_name='цена (р)')),
                ('timeStart', models.DateTimeField(verbose_name='Время начала')),
                ('timeEnd', models.DateTimeField(verbose_name='Время конца')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.human', verbose_name='Выступающий')),
                ('typeOfPost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.typeofposts', verbose_name='Тип поста')),
            ],
        ),
    ]
