# Generated by Django 3.1.4 on 2021-07-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('describe', models.TextField(verbose_name='Описание города')),
            ],
            options={
                'verbose_name': 'Название города',
                'verbose_name_plural': 'Название городов',
            },
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='Фото поста'),
        ),
        migrations.AddField(
            model_name='posts',
            name='theBest',
            field=models.BooleanField(default=False, verbose_name='Лучшее на месяц'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='game', verbose_name='Фото человека')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('points', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.human', verbose_name='Человек которого надо угадать')),
            ],
            options={
                'verbose_name': 'Игра (Угадай Комика)',
                'verbose_name_plural': 'Игра (Угадай Комика)',
            },
        ),
    ]
