# Generated by Django 3.1.4 on 2021-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210718_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
