# Generated by Django 3.1.4 on 2021-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_posts_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='цена (р)'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timeEnd',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timeStart',
            field=models.DateTimeField(verbose_name='Вход'),
        ),
    ]
