# Generated by Django 3.1.4 on 2021-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210724_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на покупку'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='linkForChat',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на чат'),
        ),
    ]
