# Generated by Django 3.1.4 on 2021-07-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210724_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Выступающий / Комик / Ведущий', 'verbose_name_plural': 'Выступающие / Комики / Ведущие'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='typeofposts',
            options={'verbose_name': 'Тип мероприятия', 'verbose_name_plural': 'Типы мероприятий'},
        ),
    ]
