# Generated by Django 3.1.4 on 2021-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_posts_costtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='chatlink',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на чат'),
        ),
        migrations.AddField(
            model_name='posts',
            name='linkRegistr',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='costType',
            field=models.IntegerField(choices=[(0, 'Обычная плата'), (1, 'Депозит'), (2, 'Донат')], default=0, verbose_name='Тип цены'),
        ),
    ]
