# Generated by Django 3.1.4 on 2021-08-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_remove_posts_chatlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='human',
        ),
        migrations.AddField(
            model_name='posts',
            name='human',
            field=models.ManyToManyField(to='index.Human', verbose_name='Выступающий'),
        ),
    ]
