# Generated by Django 3.1.7 on 2021-08-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210803_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofposts',
            options={'verbose_name': 'Тип мероприятия (скрыто)', 'verbose_name_plural': 'Типы мероприятий (скрыто)'},
        ),
    ]
