# Generated by Django 3.1.7 on 2021-08-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210804_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='Оповещено'),
        ),
    ]
