# Generated by Django 3.1.7 on 2021-08-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_posts_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='index.city', verbose_name='Город'),
        ),
    ]
