# Generated by Django 3.1.7 on 2021-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210822_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('count', models.ImageField(upload_to='', verbose_name='Количество вводов')),
            ],
            options={
                'verbose_name': 'Города пользователей',
                'verbose_name_plural': 'Города пользователей',
            },
        ),
    ]
