# Generated by Django 3.1.7 on 2021-08-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_citytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytype',
            name='count',
            field=models.IntegerField(verbose_name='Количество вводов'),
        ),
    ]
